import Link from 'next/link';
import Head from 'next/head';

export async function getStaticProps() {
  // ダミーのブログデータを取得（実際にはAPIやデータベースから取得）
  const posts = [
    { id: 1, title: '初めてのブログ記事', description: 'これは最初の投稿です' },
    { id: 2, title: '次のブログ記事', description: 'これは二番目の投稿です' },
  ];

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ここから下は通常の表示 */}
      <h1>ブログ一覧</h1>
      <ul>
        {posts.map((post) => (
          <li key={post.id}>
            <Link href={`/posts/${post.id}`}>
              <div>
                <h2>{post.title}</h2>
                <p>{post.description}</p>
              </div>
            </Link>
          </li>
        ))}
      </ul>
    </>
  );
}